[package]
name = "file_task"
version = "0.1.0"
edition = "2021"
authors = ["tcallan"]
description = "Monitor the status of tasks represented by files in folders"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.1.0"
tui = "0.19"
crossterm = "0.26"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
itertools = "0.10"
clap = { version = "4.1.14", features = ["derive"] }