[package]
name = "file_task"
version = "0.1.0"
edition = "2021"
authors = ["tcallan"]
description = "Monitor the status of tasks represented by files in folders"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.0.0-pre.14"
tui = "0.17"
crossterm = "0.23"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
itertools = "0.10"
clap = { version = "3.1.12", features = ["derive"] }